### ISSUE TITLE
XML::Error.set_handler does not work when running more than 5 tests in rspec

### ISSUE THREAD

**Issue by nburt** [xml4r/libxml-ruby#104]
When running our test suite we get a lot of these errors: `Entity: line 1: parser error : Start tag expected, '<' not found` so we've been trying silence them.

I've found that this only occurs when we run 5 or more of our tests. So, if I run 5 tests individually, none of them will print the error. If I run all 5 at once, all of them print the error.

Here is the code: 
```
XML::Error.set_handler(&XML::Error::QUIET_HANDLER)
@source = XML::Parser.string(@source_content).parse if @source_content.present?
```

Does anyone have any ideas as to what could be causing this? 

Thanks!

**Comment by cfis** [comment]
Are the tests being run in different threads?  Does 2.8.0 fix it (there was a patch for setting the error handler with different threads).

**Comment by nburt** [comment]
Is it possible that 2.7.0 would have fixed it? Looking through CircleCi at the commit that fixed the issue, it included an upgrade from 2.6.0 to 2.7.0

**Comment by cfis** [comment]
Hmm, maybe, have you checked?

**Comment by cfis** [comment]
Hopefully fixed, closing.
