### ISSUE TITLE
Does not compile against libxml2-2.9.1 on ruby-2.1.6

### ISSUE THREAD

**Issue by postmodern** [xml4r/libxml-ruby#110]
<pre>
gcc -I. -I/usr/include -I/usr/include/ruby/backward -I/usr/include -I. -I/usr/include/libxml2 -I/usr/local/include -DRUBY_EXTCONF_H=\"extconf.h\"    -fPIC -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -mtune=generic -fPIC -I/usr/include -I/usr/include/ruby/backward -I/usr/include -I. -I/usr/include/libxml2 -I/usr/local/include -m64 -o ruby_xml_node.o -c ruby_xml_node.c
ruby_xml_node.c: In function ‘rxml_node_to_s’:
ruby_xml_node.c:622:54: error: dereferencing pointer to incomplete type
     result = rxml_new_cstr((const char*) output->conv->content, xencoding);
                                                      ^
ruby_xml_node.c:624:56: error: dereferencing pointer to incomplete type
     result = rxml_new_cstr((const char*) output->buffer->content, xencoding);
                                                        ^
Makefile:225: recipe for target 'ruby_xml_node.o' failed
</pre>

**Comment by mvl22** [comment]
A colleague of ours has run into this also, for an upgrade we are keen to perform.

**Comment by cfis** [comment]
Sorry for no response on this. Will take a look.  Unless one of you has a patch?

**Comment by cfis** [comment]
Going to close this.  No issues on Ruby 2.2 and 2.3
