### ISSUE TITLE
Uncaught exception on comment-only doc

### ISSUE THREAD

**Issue by Zapotek** [xml4r/libxml-ruby#112]
Hello,

I'm trying to migrate [Arachni](https://github.com/Arachni/arachni) from Nokogiri to LibXML due to the considerable performance benefits, but I've run into an issue.

When searching a document that only includes a comment an exception is raised.

Reproduce with:
```ruby
HTML = <<HTML
    <!-- stuff -->
HTML

doc = LibXML::XML::HTMLParser.string(
    HTML,
    options: LibXML::XML::HTMLParser::Options::NOIMPLIED |
                 LibXML::XML::HTMLParser::Options::NOERROR |
                 LibXML::XML::HTMLParser::Options::NOWARNING |
                 LibXML::XML::HTMLParser::Options::RECOVER |
                 LibXML::XML::HTMLParser::Options::NONET
)

doc.parse.find( '//*' ).size
```

Result:
```
ems/ruby-2.2.3/gems/libxml-ruby-2.8.0/lib/libxml/document.rb:87:in `node=': wrong argument type nil (expected Data) (TypeError)
        from /home/zapotek/.rvm/gems/ruby-2.2.3/gems/libxml-ruby-2.8.0/lib/libxml/document.rb:87:in `context'
        from /home/zapotek/.rvm/gems/ruby-2.2.3/gems/libxml-ruby-2.8.0/lib/libxml/document.rb:123:in `find'
```

If however a tag is introduced, like so:
```ruby
HTML = <<HTML
    <!-- stuff -->
    <test/>
HTML
```

The issue goes away.

On a not so related note, I've been unable to completely silence the printed errors/warnings.
The above example (with the last HTML) will output:

```
Error: Tag test invalid at :2.
```

**Comment by cfis** [comment]
Can you add test case?

**Comment by Zapotek** [comment]
Is the test case I provided not enough?
Do you require more info?

**Comment by cfis** [comment]
Sorry, I meant a pull request adding it to the test suite that shows the failure.

**Comment by Zapotek** [comment]
To be honest I'm not familiar with the test framework you're using nor your structure.
I'd probably be better if you took a stab at it.

**Comment by cfis** [comment]
Ok, added a test case.  I can't duplicate on latest version of gem.  So hopefully it has been fixed along the way.
