### ISSUE TITLE
xml find stucks if invoked via io.popen

### ISSUE THREAD

**Issue by pierisimone** [xml4r/libxml-ruby#115]
Hi, I have a ruby program (prova5.rb) that contains a xml find. I use libxml-ruby gem. 
With Ruby 2.1.8 I have no problem, even if I execute it via "ruby prova5.rb" than if I execute it via io.popen in prova2.rb.

In a 2.2.4 environment I have success if I execute "ruby prova5.rb", but xml find stucks if I execute it via prova2.rb (io-popen).

I attach prova5.rb, prova2.rb out218.txt and out224.txt.

Same problem in all ruby 2.2 versions.
[out218.txt](https://github.com/xml4r/libxml-ruby/files/74753/out218.txt)
[out224.txt](https://github.com/xml4r/libxml-ruby/files/74752/out224.txt)

[prova2.rb.txt](https://github.com/xml4r/libxml-ruby/files/74756/prova2.rb.txt)
[prova5.rb.txt](https://github.com/xml4r/libxml-ruby/files/74757/prova5.rb.txt)

**Comment by blackwinter** [comment]
Associated Ruby issue: [#11909](https://bugs.ruby-lang.org/issues/11909).

Related libxml-ruby issue: #109 (executing `test.rb` via `IO.popen` exhibits the same problem).

**Comment by cfis** [comment]
So I could not reproduce this.  But if you still have the issue, turn off buffering on the ruby io objects.  STDOUT.sync = true
