### ISSUE TITLE
Failing to parse valid UTF-8 character

### ISSUE THREAD

**Issue by SimonMac** [xml4r/libxml-ruby#120]
We have the following node coming into our parser - <user_area name="biocide-2-set-2">DAILY 4MINS &#xA5;</user_area> - which on Ubuntu is giving an error "Exception Fatal error: Input is not proper UTF-8, indicate encoding !". As far as I can tell, this is valid UTF-8, and actually parses fine on my OSX dev box.

Any suggestions on what could be up on the Ubunutu server? I'm thinking there is a library issue somewhere.

Cheers
Simon

**Comment by cfis** [comment]
Can you post some example code?

**Comment by cfis** [comment]
Going to close this, please reopen if you still have the issue.

**Comment by SimonMac** [comment]
Seems to be an issue with libxml itself. Using the same version of libxml-ruby against different versions of libxml gives the error. Happy for this to be closed, as it looks to be beyond your control.

**Comment by cfis** [comment]
Ah interesting.  Hopefully later versions work better?
