### ISSUE TITLE
The libxml and the jruby

### ISSUE THREAD

**Issue by majioa** [xml4r/libxml-ruby#121]
When I include the gem into my gemfile I get the following error:

    Bundler could not find compatible versions for gem "libxml":
      In Gemfile:
        x_parser java was resolved to 0.1.0, which depends on
          libxml java

    Could not find gem 'libxml java', which is required by gem 'x_parser java', in
    any of the sources.

How to resolve it?

**Comment by cfis** [comment]
libxml-ruby is a c extension so would not be supported by JRuby.
