### ISSUE TITLE
default internal encoding not restored at the end of tc_encoding.rb, tc_encoding_sax.rb

### ISSUE THREAD

**Issue by boutil** [xml4r/libxml-ruby#123]
In the test tc_encoding.rb, the default internal encoding is modified, but not restored at the end in a teardown method of the TestEncoding class. This causes random failures for tests in other files relying on encoding, when tests are run in random order.
I suggest to save the state of Encoding.default_internal in the `setup` method, and restore it in `teardown`.

The file tc_encoding_sax.rb also sets the default internal encoding in `setup` but doesn't seem to modify it in the tests. But a save/restore mechanism could be also used there.

**Comment by cfis** [comment]
Nice catch.  Want to submit a patch?
