### ISSUE TITLE
Errors installing libxml gem on windows

### ISSUE THREAD

**Issue by jugonzal07** [xml4r/libxml-ruby#128]
Hello all,

I've been struggling to install libxml for quite some time now and thought I'd post here. 

When I attempt the standard command:

`gem install libxml-ruby`

I receive an error where the installer cannot find `libxml2.dll`. I found a stackoverflow thread with a similar issue and followed a user's guidelines [here](http://stackoverflow.com/a/33685307/4564486) on where to grab the missing libraries and where to include them.

If I add arguments to the install command to point at the directories with the missing libraries using the following;

`gem install libxml-ruby -- with-xml2-include=C:\Ruby200\include\libxml2 --with-iconv-include=C:\Ruby200\include`

I now get an error where the installer can’t find a “iconv.h” header which is in my C:\Ruby200\include directory. 

> C:\Users\gonz102>gem install libxml-ruby -- with-xml2-include=C:/Ruby200/include
> /libxml2 --with-iconv-include=C:/Ruby200/include
> Temporarily enhancing PATH to include DevKit...
> Building native extensions with: 'with-xml2-include=C:/Ruby200/include/libxml2 -
> -with-iconv-include=C:/Ruby200/include'
> This could take a while...
> ERROR:  Error installing libxml-ruby:
>         ERROR: Failed to build gem native extension.
> 
> C:/Ruby200/bin/ruby.exe extconf.rb with-xml2-include=C:/Ruby200/include/libx
> ml2 --with-iconv-include=C:/Ruby200/include
> checking for libxml/xmlversion.h in /opt/include/libxml2,/opt/local/include/libx
> ml2,/usr/local/include/libxml2,/usr/include/libxml2... yes
> checking for xmlParseDoc() in -lxml2... yes
> checking for rb_io_bufwrite() in ruby/io.h... yes
> creating extconf.h
> creating Makefile
> 
> make "DESTDIR="
> compiling libxml.c
> In file included from C:/Ruby200/include/libxml2/libxml/parser.h:810:0,
>                  from ruby_libxml.h:7,
>                  from libxml.c:1:
> C:/Ruby200/include/libxml2/libxml/encoding.h:28:19: fatal error: iconv.h: No suc
> h file or directory
> compilation terminated.
> make: **\* [libxml.o] Error 1
> 
> Gem files will remain installed in C:/Ruby200/lib/ruby/gems/2.0.0/gems/libxml-ru
> by-2.9.0 for inspection.
> Results logged to C:/Ruby200/lib/ruby/gems/2.0.0/gems/libxml-ruby-2.9.0/ext/libx
> ml/gem_make.out

If anyone has any suggestions as to where to go next I'd greatly appreciate it. I've been stumped on this for over a week and would gladly take any advice.

Many thanks.

**Comment by cfis** [comment]
How did you install Ruby?  Using the ruby-dev kit?

**Comment by cfis** [comment]
Going to close, please reopen if you still need help.
