### ISSUE TITLE
Attributes not being recognized

### ISSUE THREAD

**Issue by donwilde1** [xml4r/libxml-ruby#129]
libxml-ruby: ***2.9.0***
Ruby: ***2.2.5*** or ***2.3.1***
OS: Ubuntu 14.04

Nodes such as this:
```xml
<size maxLength="49" xml:space="default" />
```
Are not being parsed  by:
```ruby
  def get_attribute_by_name(a_node, a_name )
    result = nil
    if a_node.attributes?
      attrs = a_node.attributes
      attrs.each do | a |
        result = a.value if a.name == a_name
      end
    end
    result
  end
```
The file I'm parsing is: https://www.broadband-forum.org/cwmp/tr-181-2-10-0-full.xml

I've tried altering the encoding from UTF-8 with no luck. I'd appreciate if you'd see what I'm not seeing, because Attributes are so basic they should Just Work.

**Comment by cfis** [comment]
You aren't providing much information about what attributes you are having issues with...but I'd guess it has to do with namespaces.  If you look in the test folder, you'll see see a bunch of attribute tests cases that can hopefully point you in the right direction.

**Comment by donwilde1** [comment]
Sorry, just noticed that my XML dropped out. :) Everything in that document is in the root namespace. I'll go dig in the test cases, thanks!

**Comment by donwilde1** [comment]
Okay, I built a small test program. It does work, but somehow the **xml:space="default"** attributes are getting eliminated.
Can someone please educate me as to why that might be? AFAICT, they are everywhere and there's only one namespace: default. Why would my program skip printing them? Is it a quirk of libxml-ruby or is it real, and why does my larger program -- using exactly the same Helpers -- fail.

```ruby
#! /usr/bin/env ruby

require 'xml'

class XMLEater

	def initialize
		file_name = './data/tr-181-2-10-0-full.xml'
		@results = File.new( './results.txt', 'w' )
		parser = XML::Parser.file( file_name )
		@root = parser.parse.root
		@model = get_the_only_one_of_a_class( @root.children, 'model' )
		@model.children.each do | a_node |
			recurse_all_children( a_node )
		end
		@results.close
	end
	
	def recurse_all_children( a_node )
		if a_node.name == 'size'
			if a_node.attributes?
				maxLength = get_attribute_by_name( a_node, 'maxLength' )
				minLength = get_attribute_by_name( a_node, 'minLength' )
				@results.puts( a_node.to_s )
				@results.puts( ' maxLength: ' + maxLength.to_s ) if !maxLength.nil?
				@results.puts( ' minLength: ' + minLength.to_s ) if !minLength.nil?
			end	
		end
		if a_node.children?
			a_node.children.each do | n |
				recurse_all_children( n )
			end
		end
		
	end
	
	#Helpers
	
  def select_all_members_of_a_class(a_node_array, a_node_class_name )
    result = a_node_array.select do | a_node |
      !a_node.nil? && a_node.name == a_node_class_name
    end
    result
  end

  def get_the_only_one_of_a_class(a_node_array, a_node_class_name )
    result = nil
    a_node_array.each do | a_node |
      if a_node.name == a_node_class_name
        result = a_node
        break
      end
    end
    result
  end

  def get_attribute_by_name(a_node, a_name )
    result = nil
    if a_node.attributes?
      attrs = a_node.attributes
      attrs.each do | a |
        n = a.name
        v = a.value
        result = a.value if a.name == a_name
      end
    end
    result
  end

  def get_all_attributes( a_node )
    attributes_hash = {}
    if a_node.attributes?
      count = 0
      attributes = a_node.attributes
      attributes.each do | a |
        attributes_hash[ a.name ] = a.value
      end
    end
    attributes_hash
  end
	
end

eater = XMLEater.new
```

**Comment by cfis** [comment]
http://xml4r.github.io/libxml-ruby/rdoc/LibXML/XML/XPath.html, see "Working With Default Namespaces"

**Comment by cfis** [comment]
And:

http://xml4r.github.io/libxml-ruby/rdoc/LibXML/XML/Attributes.html

**Comment by donwilde1** [comment]
Okay, I just figured out my bug(s). The libxml-ruby is working fine. It's my head that isn't. I was looking for attributes of a child node but referring to the parent. **>8^%**
