### ISSUE TITLE
Unable to install libxml-ruby on Windows

### ISSUE THREAD

**Issue by anshul-kothari** [xml4r/libxml-ruby#131]
Guys, i am getting error while installing libxml-ruby. 

$ gem install libxml-ruby --platform=ruby  -- --with-xml2-include=D:/Ruby22-x64
/include --with-xml2-lib=D:/Ruby22-x64/lib --with-iconv-lib=D:/Ruby22-x64/lib
Temporarily enhancing PATH to include DevKit...
Building native extensions with: '--with-xml2-include=D:/Ruby22-x64/include --with-xml2-lib=D:/Ruby22-x64/lib --with-iconv-lib=D:/Ruby22-x64/lib'
This could take a while...
ERROR:  Error installing libxml-ruby:
        ERROR: Failed to build gem native extension.

    d:/Ruby22-x64/bin/ruby.exe -r ./siteconf20161207-9028-qq1j1p.rb extconf.rb --with-xml2-include=D:/Ruby22-x64/include --with-xml2-lib=D:/Ruby22-x64/lib --with-iconv-lib=D:/Ruby22-x64/lib
checking for libxml/xmlversion.h in /opt/include/libxml2,/opt/local/include/libxml2,/usr/local/include/libxml2,/usr/include/libxml2... yes
checking for xmlParseDoc() in -lxml2... no
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=d:/Ruby22-x64/bin/$(RUBY_BASE_NAME)
        --with-xml2-config
        --without-xml2-config
        --with-xml2-dir
        --without-xml2-dir
        --with-xml2-include=${xml2-dir}/include
        --with-xml2-lib=${xml2-dir}/lib
        --with-xml2lib
        --without-xml2lib
 extconf failure: need libxml2.

    Install the library or try one of the following options to extconf.rb:

      --with-xml2-config=/path/to/xml2-config
      --with-xml2-dir=/path/to/libxml2
      --with-xml2-lib=/path/to/libxml2/lib
      --with-xml2-include=/path/to/libxml2/include

extconf failed, exit code 1

Gem files will remain installed in d:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/libxml-ruby-2.9.0 for inspection.
Results logged to d:/Ruby22-x64/lib/ruby/gems/2.2.0/extensions/x64-mingw32/2.2.0/libxml-ruby-2.9.0/gem_make.out

**Comment by cfis** [comment]
Try this:
--with-xml2-include=D:/Ruby22-x64/include/libxml2
