### ISSUE TITLE
The \r is changed to \n after parsing

### ISSUE THREAD

**Issue by chen120** [xml4r/libxml-ruby#132]
I was using libxml to parse a xml string. But the \r was changed to \n after parsing. Here is what I did in rails console,

```
>> xml = "<a>bb\r</a>"
=> "<a>bb\r</a>"
>> doc = XML::Document.string(xml, :encoding => XML::Encoding::UTF_8)
=> <?xml version="1.0" encoding="UTF-8"?>
<a>bb
</a>
>> doc.find("/a")[0].content
=> "bb\n"
```
Is that a way I could avoid this?

**Comment by chen120** [comment]
Could anyone help on this?

**Comment by cfis** [comment]
I think this is part of libxml, not the ruby bindings.

See http://stackoverflow.com/a/16787890.

**Comment by chen120** [comment]
Thanks a lot!
