### ISSUE TITLE
Memory leaks on version 3.0.0 and ruby 2.3.3

### ISSUE THREAD

**Issue by MOZGIII** [xml4r/libxml-ruby#137]
We have leaking memory with ruby 2.3.3 and libxml-ruby 3.0.0. Is this supposed to be that way (changelog mentions ruby 2.4+) or is it a bug?

If this is a bug, I can provide jemalloc heap dumps that prove the leaks and describe our use patterns of the library (nothing special really, maybe just the fact that we reparent nodes to different documents may be significant).

We've currently rolled back to 2.9.0 which doesn't leak.

**Comment by cfis** [comment]
Definitely not supposed to be that way.  Posting the heap dumps would be great, thanks.

**Comment by bnil** [comment]
We ran in to this issue as well, ruby 2.3.4, rails 4.2.10, nokogiri 1.8.1. Segfault with libxml-ruby 3.0.0 seems to work fine with 2.9.0

With 3.0.0, it doesn't segfault after GC.stop, but that's not a great solution.

[debug.txt](https://github.com/xml4r/libxml-ruby/files/1547404/debug.txt)

**Comment by cfis** [comment]
Is there any additional information you could provide?

**Comment by MOZGIII** [comment]
I don't have access to the project anymore. The xmls we were working with were huge sometimes, like 200 MBs. Hope this helps.
