### ISSUE TITLE
problem with patterns 

### ISSUE THREAD

**Issue by thiaguerd** [xml4r/libxml-ruby#138]
The value 'CX' is not accepted by the pattern '[!-ÿ]{1}[ -ÿ]{0,}[!-ÿ]{1}|[!-ÿ]{1}'.
The value '57' is not accepted by the pattern '[!-ÿ]{1}[ -ÿ]{0,}[!-ÿ]{1}|[!-ÿ]{1}'.

**Comment by cfis** [comment]
Sorry, not following.  Could you provide more details?

**Comment by thiaguerd** [comment]
I have a basic type string
````xml
<xs:simpleType name="TString">
	<xs:annotation>
		<xs:documentation>type string generic</xs:documentation>
	</xs:annotation>
	<xs:restriction base="xs:string">
		<xs:whiteSpace value="preserve"/>
		<xs:pattern value="[!-ÿ]{1}[ -ÿ]{0,}[!-ÿ]{1}|[!-ÿ]{1}"/>
	</xs:restriction>
</xs:simpleType>
````
I use a basic type string here
````xml
<xs:element name="my_name_tag" type="TString">
	<xs:annotation>
		<xs:documentation>info of my_name_tag</xs:documentation>
	</xs:annotation>
</xs:element>
````

the pattern works in ruby but not when I try validate using this lib

**Comment by cfis** [comment]
Seems like something that is not supported by the xml schema standard.  See:

https://www.regular-expressions.info/xml.html

If you think this is a bug, sounds like it should be submitted to the libxml2 project (what libxml-ruby uses underneath).
