### ISSUE TITLE
Can't update to 3.0.0 on Windows

### ISSUE THREAD

**Issue by cmcollin41** [xml4r/libxml-ruby#139]
Hi, I can't update to 3.0.0 on Windows. Here is my error:

*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=C:/RailsInstaller/Ruby2.2.0/bin/$(RUBY_BASE_NAME)
        --with-xml2-config
        --without-xml2-config
        --with-xml2-dir
        --without-xml2-dir
        --with-xml2-include
        --without-xml2-include=${xml2-dir}/include
        --with-xml2-lib
        --without-xml2-lib=${xml2-dir}/lib
 extconf failure: need libxml2.

    Install the library or try one of the following options to extconf.rb:

      --with-xml2-config=/path/to/xml2-config
      --with-xml2-dir=/path/to/libxml2
      --with-xml2-lib=/path/to/libxml2/lib
      --with-xml2-include=/path/to/libxml2/include

extconf failed, exit code 1

Gem files will remain installed in
C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/libxml-ruby-3.0.0 for
inspection.
Results logged to
C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/extensions/x86-mingw32/2.2.0/libxml-ruby-3.0.0/gem_make.out

**Comment by cmcollin41** [comment]
Here is my mkmf.log file:

find_header: checking for libxml/xmlversion.h in /opt/include/libxml2,/opt/local/include/libxml2,/usr/local/include/libxml2,/usr/include/libxml2... -------------------- no

"gcc -o conftest.exe -IC:/RailsInstaller/Ruby2.2.0/include/ruby-2.2.0/i386-mingw32 -IC:/RailsInstaller/Ruby2.2.0/include/ruby-2.2.0/ruby/backward -IC:/RailsInstaller/Ruby2.2.0/include/ruby-2.2.0 -I. -DFD_SETSIZE=2048 -D_WIN32_WINNT=0x0501 -D__MINGW_USE_VC2005_COMPAT -D_FILE_OFFSET_BITS=64   -O3 -fno-omit-frame-pointer -fno-fast-math -g -Wall -Wextra -Wno-unused-parameter -Wno-parentheses -Wno-long-long -Wno-missing-field-initializers -Wunused-variable -Wpointer-arith -Wwrite-strings -Wdeclaration-after-statement -Wimplicit-function-declaration -Wdeprecated-declarations -Wno-packed-bitfield-compat conftest.c  -L. -LC:/RailsInstaller/Ruby2.2.0/lib -L.      -lmsvcrt-ruby220  -lshell32 -lws2_32 -liphlpapi -limagehlp -lshlwapi  "
checked program was:
/* begin */
1: #include "ruby.h"
2: 
3: #include <winsock2.h>
4: #include <windows.h>
5: int main(int argc, char **argv)
6: {
7:   return 0;
8: }
/* end */

"gcc -E -IC:/RailsInstaller/Ruby2.2.0/include/ruby-2.2.0/i386-mingw32 -IC:/RailsInstaller/Ruby2.2.0/include/ruby-2.2.0/ruby/backward -IC:/RailsInstaller/Ruby2.2.0/include/ruby-2.2.0 -I. -DFD_SETSIZE=2048 -D_WIN32_WINNT=0x0501 -D__MINGW_USE_VC2005_COMPAT -D_FILE_OFFSET_BITS=64   -O3 -fno-omit-frame-pointer -fno-fast-math -g -Wall -Wextra -Wno-unused-parameter -Wno-parentheses -Wno-long-long -Wno-missing-field-initializers -Wunused-variable -Wpointer-arith -Wwrite-strings -Wdeclaration-after-statement -Wimplicit-function-declaration -Wdeprecated-declarations -Wno-packed-bitfield-compat  conftest.c -o conftest.i"
conftest.c:5:31: fatal error: libxml/xmlversion.h: No such file or directory
compilation terminated.
checked program was:
/* begin */
1: #include "ruby.h"
2: 
3: #include <winsock2.h>
4: #include <windows.h>
5: #include <libxml/xmlversion.h>
/* end */

"gcc -E -IC:/RailsInstaller/Ruby2.2.0/include/ruby-2.2.0/i386-mingw32 -IC:/RailsInstaller/Ruby2.2.0/include/ruby-2.2.0/ruby/backward -IC:/RailsInstaller/Ruby2.2.0/include/ruby-2.2.0 -I. -DFD_SETSIZE=2048 -D_WIN32_WINNT=0x0501 -D__MINGW_USE_VC2005_COMPAT -D_FILE_OFFSET_BITS=64   -O3 -fno-omit-frame-pointer -fno-fast-math -g -Wall -Wextra -Wno-unused-parameter -Wno-parentheses -Wno-long-long -Wno-missing-field-initializers -Wunused-variable -Wpointer-arith -Wwrite-strings -Wdeclaration-after-statement -Wimplicit-function-declaration -Wdeprecated-declarations -Wno-packed-bitfield-compat -I/opt/include/libxml2 conftest.c -o conftest.i"
conftest.c:5:31: fatal error: libxml/xmlversion.h: No such file or directory
compilation terminated.
checked program was:
/* begin */
1: #include "ruby.h"
2: 
3: #include <winsock2.h>
4: #include <windows.h>
5: #include <libxml/xmlversion.h>
/* end */

"gcc -E -IC:/RailsInstaller/Ruby2.2.0/include/ruby-2.2.0/i386-mingw32 -IC:/RailsInstaller/Ruby2.2.0/include/ruby-2.2.0/ruby/backward -IC:/RailsInstaller/Ruby2.2.0/include/ruby-2.2.0 -I. -DFD_SETSIZE=2048 -D_WIN32_WINNT=0x0501 -D__MINGW_USE_VC2005_COMPAT -D_FILE_OFFSET_BITS=64   -O3 -fno-omit-frame-pointer -fno-fast-math -g -Wall -Wextra -Wno-unused-parameter -Wno-parentheses -Wno-long-long -Wno-missing-field-initializers -Wunused-variable -Wpointer-arith -Wwrite-strings -Wdeclaration-after-statement -Wimplicit-function-declaration -Wdeprecated-declarations -Wno-packed-bitfield-compat -I/opt/local/include/libxml2 conftest.c -o conftest.i"
conftest.c:5:31: fatal error: libxml/xmlversion.h: No such file or directory
compilation terminated.
checked program was:
/* begin */
1: #include "ruby.h"
2: 
3: #include <winsock2.h>
4: #include <windows.h>
5: #include <libxml/xmlversion.h>
/* end */

"gcc -E -IC:/RailsInstaller/Ruby2.2.0/include/ruby-2.2.0/i386-mingw32 -IC:/RailsInstaller/Ruby2.2.0/include/ruby-2.2.0/ruby/backward -IC:/RailsInstaller/Ruby2.2.0/include/ruby-2.2.0 -I. -DFD_SETSIZE=2048 -D_WIN32_WINNT=0x0501 -D__MINGW_USE_VC2005_COMPAT -D_FILE_OFFSET_BITS=64   -O3 -fno-omit-frame-pointer -fno-fast-math -g -Wall -Wextra -Wno-unused-parameter -Wno-parentheses -Wno-long-long -Wno-missing-field-initializers -Wunused-variable -Wpointer-arith -Wwrite-strings -Wdeclaration-after-statement -Wimplicit-function-declaration -Wdeprecated-declarations -Wno-packed-bitfield-compat -I/usr/local/include/libxml2 conftest.c -o conftest.i"
conftest.c:5:31: fatal error: libxml/xmlversion.h: No such file or directory
compilation terminated.
checked program was:
/* begin */
1: #include "ruby.h"
2: 
3: #include <winsock2.h>
4: #include <windows.h>
5: #include <libxml/xmlversion.h>
/* end */

"gcc -E -IC:/RailsInstaller/Ruby2.2.0/include/ruby-2.2.0/i386-mingw32 -IC:/RailsInstaller/Ruby2.2.0/include/ruby-2.2.0/ruby/backward -IC:/RailsInstaller/Ruby2.2.0/include/ruby-2.2.0 -I. -DFD_SETSIZE=2048 -D_WIN32_WINNT=0x0501 -D__MINGW_USE_VC2005_COMPAT -D_FILE_OFFSET_BITS=64   -O3 -fno-omit-frame-pointer -fno-fast-math -g -Wall -Wextra -Wno-unused-parameter -Wno-parentheses -Wno-long-long -Wno-missing-field-initializers -Wunused-variable -Wpointer-arith -Wwrite-strings -Wdeclaration-after-statement -Wimplicit-function-declaration -Wdeprecated-declarations -Wno-packed-bitfield-compat -I/usr/include/libxml2 conftest.c -o conftest.i"
conftest.c:5:31: fatal error: libxml/xmlversion.h: No such file or directory
compilation terminated.
checked program was:
/* begin */
1: #include "ruby.h"
2: 
3: #include <winsock2.h>
4: #include <windows.h>
5: #include <libxml/xmlversion.h>
/* end */

--------------------

**Comment by cfis** [comment]
Looks like the compiler cannot find the libxml2 header files.  You'll want to use the --with-xml2-include option.

gem install libxml-ruby -- --with-xml2-include=<wherever the header files are>
