### ISSUE TITLE
Reader#expand causing Segmentation fault

### ISSUE THREAD

**Issue by ljulliar** [xml4r/libxml-ruby#142]
I'm using XML::REader to split an XML file made of 100 000 records of the same kind into smaller chuncks of a thousand records (Ubuntu 16.04 64 bits, ruby 2.3.1, libxml-ruby 3.0.0)
My pseudo is typically

```
while reader.read do
  if reader.name == 'Product'
    file.write(reader.expand)
  end
  reader.next
end
```

The script crashes after a few hundreds records. see crash dump below. Amazingly enough if i replace 'reader.expand' by 'reader.expand.dup' the script stops crashing. Can this be because the node doesn't live long enough for the actual write operation to happen ?

[crash_stack.txt](https://github.com/xml4r/libxml-ruby/files/1207492/crash_stack.txt)

**Comment by cfis** [comment]
Remember the node is invalidated immediately upon the next read.  Duping it at least provides you with a valid node.
