### ISSUE TITLE
installation problem

### ISSUE THREAD

**Issue by gorn** [xml4r/libxml-ruby#143]
I am on debian and have llibxml2 package (2.9.4) installed. Still this fails

$ sudo gem install libxml-ruby                                              
Building native extensions.  This could take a while...                                                   
ERROR:  Error installing libxml-ruby:                                                                     
        ERROR: Failed to build gem native extension.                                                      
                                                                                                          
    current directory: /var/lib/gems/2.3.0/gems/libxml-ruby-3.0.0/ext/libxml                              
/usr/bin/ruby2.3 -r ./siteconf20170908-17659-mcmmoq.rb extconf.rb                                         
checking for libxml/xmlversion.h in /opt/include/libxml2,/opt/local/include/libxml2,/usr/local/include/libxml2,/usr/include/libxml2... no                                                                           
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/usr/bin/$(RUBY_BASE_NAME)2.3
        --with-xml2-config
        --without-xml2-config
        --with-xml2-dir
        --without-xml2-dir
        --with-xml2-include
        --without-xml2-include=${xml2-dir}/include
        --with-xml2-lib
        --without-xml2-lib=${xml2-dir}/lib
 extconf failure: need libxml2.

    Install the library or try one of the following options to extconf.rb:

      --with-xml2-config=/path/to/xml2-config
      --with-xml2-dir=/path/to/libxml2
      --with-xml2-lib=/path/to/libxml2/lib
      --with-xml2-include=/path/to/libxml2/include

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /var/lib/gems/2.3.0/extensions/x86_64-linux/2.3.0/libxml-ruby-3.0.0/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /var/lib/gems/2.3.0/gems/libxml-ruby-3.0.0 for inspection.
Results logged to /var/lib/gems/2.3.0/extensions/x86_64-linux/2.3.0/libxml-ruby-3.0.0/gem_make.out

**Comment by gorn** [comment]
Ok, I have resolved it by install ing libxml2-dev package :)) 

Sorry

**Comment by athix** [comment]
@gorn thanks for posting your fix, found this via Google and it solved it for me as well. :smile:
