### ISSUE TITLE
 `require': cannot load such file -- libxml_ruby (LoadError)

### ISSUE THREAD

**Issue by miladhashemi** [xml4r/libxml-ruby#144]
i'm new to ruby.
i would like use this library in my script but i got this error.
`require 'rubygems'
require 'libxml'
require 'couchrest'

include LibXML

class JamendoCallbacks
	include XML::SaxParser::Callbacks
	def initialize()
		@db = CouchRest.database!("http://localhost:5984/music")
		@count = 0
		@max = 100 # maximum number to insert
		@stack = []
		@artist = nil
		@album = nil
		@track = nil
		@tag = nil
		@buffer = nil
	end
	def on_start_element(element, attributes)
		case element
		when 'artist'
			@artist = { :albums => [] }
			@stack.push @artist
		when 'album'
			@album = { :tracks => [] }
			@artist[:albums].push @album
			@stack.push @album
		when 'track'
			@track = { :tags => [] }
			@album[:tracks].push @track
			@stack.push @track
		when 'tag'
			@tag = {}
			@track[:tags].push @tag
			@stack.push @tag
		when 'Artists', 'Albums', 'Tracks', 'Tags'
			# ignore
		else
			@buffer = []
		end
	end
	def on_characters(chars)
		@buffer << chars unless @buffer.nil?
	end
	def on_end_element(element)
		case element
		when 'artist'
			@stack.pop
			@artist['_id'] = @artist['id'] # reuse Jamendo's artist id for doc _id
			@artist[:random] = rand
			@db.save_doc(@artist, false, true)
			@count += 1
			if !@max.nil? && @count >= @max
				on_end_document
			end
			if @count % 500 == 0
				puts " #{@count} records inserted"
			end
		when 'album', 'track', 'tag'
			top = @stack.pop
			top[:random] = rand
		when 'Artists', 'Albums', 'Tracks', 'Tags'
			# ignore
		else
			if @stack[-1] && @buffer
				@stack[-1][element] = @buffer.join.force_encoding('utf-8')
				@buffer = nil
			end
		end
	end
	def on_end_document()
		puts "TOTAL: #{@count} records inserted"
		exit(1)
	end
end`

**Comment by KapilMetacube** [comment]
is it related to #42 ?

**Comment by cfis** [comment]
Maybe.  Do you have a traceback?

**Comment by cfis** [comment]
Going to close, please reopen if you need.

**Comment by KapilMetacube** [comment]
This gem was a dependency of ruby twilio-ruby, which coincidently replaced it with` nokogiri` after few days I encountered this issue. So I'm no more using this.

More info [here](https://github.com/twilio/twilio-ruby/issues/337#issuecomment-345140807)
