### ISSUE TITLE
Warning: method redefined; discarding old annotation

### ISSUE THREAD

**Issue by Dorian** [xml4r/libxml-ruby#145]
Happens when running `bundle exec rake` on [`rails/rails`](github.com/rails/rails):

```ruby
/Users/d/.rvm/gems/ruby-2.4.1/gems/libxml-ruby-3.0.0/lib/libxml/schema/type.rb:8: warning: method redefined; discarding old annotation
/Users/d/.rvm/gems/ruby-2.4.1/gems/libxml-ruby-3.0.0/lib/libxml/schema/element.rb:18: warning: method redefined; discarding old annotation
```

**Comment by composerinteralia** [comment]
Has something to do with the fact that the Ruby methods are overriding these C methods:

https://github.com/xml4r/libxml-ruby/blob/fdc50f21fa63706cc0160b873eea6e5772aea91d/ext/libxml/ruby_xml_schema_type.c#L258
https://github.com/xml4r/libxml-ruby/blob/fdc50f21fa63706cc0160b873eea6e5772aea91d/ext/libxml/ruby_xml_schema_element.c#L93

**Comment by cfis** [comment]
Yes, that's definitely it.  Cleaned up now.  Thanks for the report!
