### ISSUE TITLE
NONET not respected in schema validation

### ISSUE THREAD

**Issue by gucki** [xml4r/libxml-ruby#153]
I set NONET on all involved documents but the network is still contacted:

    xml = LibXML::XML::Document.string(xml_string, options: LibXML::XML::Parser::Options::NONET)
    Dir.chdir(File.dirname(xsd_path)) do
      schema_document = LibXML::XML::Document.file(xsd_path, options: LibXML::XML::Parser::Options::NONET)
      schema = LibXML::XML::Schema.document(schema_document)
      xml.validate_schema(schema)
    end

**Comment by cfis** [comment]
Sorry this was never answered. I verified the bindings are passing the NOENT option to libxml2. The issue might be in the creation of the XML schema, which libxml2 defines via the xmlSchemaParserCtxt. But I don't see an api for setting options on that parser context.

**Comment by nwellnhof** [comment]
Unfortunately, libxml2 doesn't offer an API to set parser options for parsing schemas yet.

**Comment by cfis** [comment]
Going to close this since it is a limitation in libxml2 and not in the bindings (I just checked again for an API to use but don't see one).

**Comment by nwellnhof** [comment]
It's a long-standing issue that libxml2 doesn't offer a way to pass parser options to the schema validator. I hope to get this addressed soon.
