### ISSUE TITLE
libxml-ruby 3.0.0 performance loss moving from ruby 2.1.0 to ruby 2.6.0

### ISSUE THREAD

**Issue by chrisdtaylor** [xml4r/libxml-ruby#159]
I have a tool that I would like to move to ruby 2.6.0 from ruby 2.1.0.  In both cases, I have installed libxml-ruby for the particular ruby baseline such that switching the tool to the later ruby was as simple as changing the she-bang line in the tool.  That is, nothing about the use of libxml here has changed.

I'm finding that the same process runs significantly slower.  It also appears to be consuming more memory than before.  I (naively?) expected the opposite to occur.

Any idea why this might have happened?  I didn't personally install the libxml-ruby gem in either case - maybe there were some optimizations left out of the 2.6.0 install?

**Comment by cfis** [comment]
I wouldn't expect anything to change, assuming you are using the same version of libxml2 under the covers and the same version or the libxml-ruby gem.

**Comment by chrisdtaylor** [comment]
I dug a bit deeper.  It looks like the libxml portion of my tool is not the issue.  Something else changed in ruby 2.1.0 -> 2.6.0 that is causing a perf issue.

Sorry for the false alarm!

**Comment by cfis** [comment]
Cool - that makes more sense.
