### ISSUE TITLE
Fails to build against libxml2 2.9.10

### ISSUE THREAD

**Issue by utkarsh2102** [xml4r/libxml-ruby#161]
Hi,

Thanks for your work on libxml-ruby so far :)
However, it fails to build against libxml2 2.9.10 with the following error:

```
Finished in 3.018297s, 113.9716 runs/s, 13993.6539 assertions/s.

  1) Failure:
TestSaxParser#test_parse_error [/build/ruby-libxml-3.1.0/test/test_sax_parser.rb:257]:
--- expected
+++ actual
@@ -1,3 +1,3 @@
 # encoding: UTF-8
 #    valid: true
-"error: Fatal error: Premature end of data in tag Results line 1 at :2."
+"error: Fatal error: EndTag: '</' not found at :2."


  2) Failure:
TestDtd#test_invalid [/build/ruby-libxml-3.1.0/test/test_dtd.rb:87]:
--- expected
+++ actual
@@ -1,3 +1 @@
-# encoding: UTF-8
-#    valid: true
-"invalid"
+nil


344 runs, 42237 assertions, 2 failures, 0 errors, 0 skips
```

Can you please take a quick look at it?

**Comment by cfis** [comment]
Those aren't build errors...they are test errors. But yes.

**Comment by mr-c** [comment]
Here is a naive patch: https://salsa.debian.org/ruby-team/ruby-libxml/-/blob/5f99ba465bebf92bf0b07bbd723640201a5c7243/debian/patches/newer_libxml_fix_tests

**Comment by mapreri** [comment]
For people that would like a reference, this is the relevant libxml2 change that broke the test:
https://gitlab.gnome.org/GNOME/libxml2/commit/62150ed2ab19a4dd76c15acc62c7d923d9f3b2cc

**Comment by cfis** [comment]
Thanks for that link!
