### ISSUE TITLE
Segfault upon garbage collection with certain DTD files

### ISSUE THREAD

**Issue by azimux** [xml4r/libxml-ruby#162]
Can be reproduced with the following script:

```
require "libxml"
require "open-uri"

dtd = open("https://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd").read
LibXML::XML::Dtd.new(dtd)
GC.start
```

We tried this with different DTDs, even small ones.

Reproduced on:

libxml-ruby 3.1.0
Ubuntu 18.04
libxml2 2.9.4
Ruby 2.5.7

We've also reproduced it on:

libxml-ruby 3.1.0
Ubuntu 16.04
libxml2 2.9.3
Ruby 2.5.3

It's also been reproduced on a Mac.

**Comment by ctcherry** [comment]
I'm able to reproduce even with no actual dtd content. The following segfaults:
```
require "libxml"
LibXML::XML::Dtd.new('')
GC.start
```
ruby 2.5.3p105 (2018-10-18 revision 65156) [x86_64-darwin17]
libxml-ruby 3.1.0
OSX 10.13.6

**Comment by cfis** [comment]
Thanks for the report!
