### ISSUE TITLE
Is 3.2.0 an official release?

### ISSUE THREAD

**Issue by mattbrictson** [xml4r/libxml-ruby#163]
libxml-ruby 3.2.0 is [available to download](https://rubygems.org/gems/libxml-ruby/versions/3.2.0) on rubygems.org but there is no v3.2.0 tag in this git repo, no release notes, and the code itself in the master branch still is [version 3.1.0](https://github.com/xml4r/libxml-ruby/blob/master/ext/libxml/ruby_xml_version.h#L4).

Is the 3.2.0 gem on rubygems legit and safe to use?

**Comment by cfis** [comment]
Yes it is. Sorry, I thought I had pushed the changes and tag.  They are now pushed. Thanks for the heads-up.
