### ISSUE TITLE
from ASCII-8BIT to UTF-8 (Encoding::UndefinedConversionError)

### ISSUE THREAD

**Issue by pulver** [xml4r/libxml-ruby#164]
Hello - thank you for maintaining this useful library.

Running the following script
```
require 'libxml'

File.open('test.xml', 'w', encoding: 'UTF-8') do |file|
  writer = LibXML::XML::Writer::io file
  writer.start_document encoding: LibXML::XML::Encoding::UTF_8

  writer.write_element 'Name', 'François'.encode(Encoding::UTF_8)

  writer.end_document
end
```
produces the error:
```
Traceback (most recent call last):
	4: from test.rb:3:in `<main>'
	3: from test.rb:3:in `open'
	2: from test.rb:9:in `block in <main>'
	1: from test.rb:9:in `end_document'
test.rb:9:in `write': "\xC3" from ASCII-8BIT to UTF-8 (Encoding::UndefinedConversionError)
```
When I use the `LibXML::XML::Writer::file` class method it is ok - but for my application I need to pass in the IO object. This happens with or without the `encode(Encoding::UTF_8)` call.

Any suggestions?

```
$ ruby --version
ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-linux]
$ pacman -Qi libxml2
Name            : libxml2
Version         : 2.9.10-1
$ gem info libxml-ruby
libxml-ruby (3.2.0)
```

**Comment by cfis** [comment]
Hmm, that looks like a bug introduced by removing the Ruby 1.8 specific code in the last release. And there isn't a test for using an io object in the test_writer.rb file.  So...will have to look into this. Thanks for the report.

**Comment by cfis** [comment]
Sorry this took so long to look at. Turns out this never worked for an io stream.

Its now fixed. The writer reads the encoding from the io stream, so you don't have to set it on start_document.
