### ISSUE TITLE
Failed to set options for parsing

### ISSUE THREAD

**Issue by crosspath** [xml4r/libxml-ruby#167]
```ruby
require 'libxml'
options = LibXML::XML::Parser::Options::NOWARNING # => 64
context = LibXML::XML::Parser::Context.io(File.open('/dev/null','r'))
context.options = options
context.options # => 0
```

Expected result: `64` for last line.

Selected file does not matter.

**Comment by crosspath** [comment]
```ruby
LibXML::XML::VERSION # 3.1.0
```

**Comment by cfis** [comment]
I know it surprising, but as expected. If you look at the libxml source code, when libxml-ruby calls the method xmlCtxtUseOptions it eventually does this:

if (options & XML_PARSE_NOWARNING) {
        ctxt->sax->warning = NULL;
        options -= XML_PARSE_NOWARNING;
    }

Notice it sets the sax warning to null, and then removes XML_PARSE_NOWARNING from the options. Thus calling context.options will return 0.
