### ISSUE TITLE
Warning "config includes `BUNDLE_BUILD__LIBXML-RUBY`, which contains the dash character (`-`)."

### ISSUE THREAD

**Issue by ruvaleev** [xml4r/libxml-ruby#174]
After update to Bundler version 2.2.26, I get this warning

```bash
Your /Users/ruslan/.bundle/config config includes `BUNDLE_BUILD__LIBXML-RUBY`, which contains the dash character (`-`).
This is deprecated, because configuration through `ENV` should be possible, but `ENV` keys cannot include dashes.
Please edit /Users/ruslan/.bundle/config and replace any dashes in configuration keys with a triple underscore (`___`).
```

My **.bundle/config** file:

```txt
---
BUNDLE_BUILD__LIBXML-RUBY: "--with-xml2-config=/usr/local/opt/libxml2/bin/xml2-config"
BUNDLE_BUILD__LIBV8: "--with-system-v8"
BUNDLE_GITHUB__HTTPS: "true"
```

If I remove first variable or change its name, say, from `BUNDLE_BUILD__LIBXML-RUBY` to `BUNDLE_BUILD__LIBXMLRUBY` (eliminating `-` symbol) this warning disappears. How can I avoid this warning without breaking **libxml-ruby** functionality? Is there any way for that?

Thanks in advance!

**Comment by cfis** [comment]
Hmm...I'd say replace with a underscore. Want to submit a patch?

**Comment by fade2black** [comment]
@cfis Can't you simply to submit a **sneaky fix** for this issue too? 😉 But don't forget to blame the author too that the changes are breaking changes and he/she needs to update his/her APIs as you usually do.

**Comment by fade2black** [comment]
@cfis With pleasure. However, how about you first start to learn to tell apart breaking changes from your bugs in the code?  Learning Ruby hashes and keyword params...? 😉

**Comment by cfis** [comment]
I'm going to close this because it looks like bundler fixed it somewhere along the line. 

Specifically, If I do:

```
bundle config build.libxml-ruby --with-xml2-include=/ucrt64/include/libxml2
```

Then my bundler config ends up as:

```
---
BUNDLE_BUILD__LIBXML___RUBY: "--with-xml2-include=C:/msys64/ucrt64/include/libxml2"
```

Seems ok?
