### ISSUE TITLE
Uncaught exception: cannot load such file -- libxml_ruby even if it's installed. 

### ISSUE THREAD

**Issue by SP8890** [xml4r/libxml-ruby#178]
1. Gem Environment  : 
RubyGems Environment:
  - RUBYGEMS VERSION: 2.7.6
  - RUBY VERSION: 2.5.3 (2018-10-18 patchlevel 105) [x64-mingw32]
  - INSTALLATION DIRECTORY: C:/Ruby25-x64/lib/ruby/gems/2.5.0
  - USER INSTALLATION DIRECTORY: C:/Users/Sachin/.gem/ruby/2.5.0
  - RUBY EXECUTABLE: C:/Ruby25-x64/bin/ruby.exe
  - EXECUTABLE DIRECTORY: C:/Ruby25-x64/bin
  - SPEC CACHE DIRECTORY: C:/Users/Sachin/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: C:/ProgramData
  - RUBYGEMS PLATFORMS:
    - ruby
    - x64-mingw32
  - GEM PATHS:
     - C:/Ruby25-x64/lib/ruby/gems/2.5.0
     - C:/Users/Sachin/.gem/ruby/2.5.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - C:\Program Files (x86)\Common Files\Oracle\Java\javapath
     - C:\Program Files\Common Files\Oracle\Java\javapath
     - C:\Windows\System32
     - C:\Windows
     - C:\Windows\System32\wbem
     - C:\Windows\System32\WindowsPowerShell\v1.0\
     - C:\Windows\System32\OpenSSH\
     - C:\Program Files\SourceGear\Common\DiffMerge\
     - C:\Program Files\Java\jdk-16.0.1\bin
     - C:\Program Files\apache-maven-3.8.1\bin
     - C:\Program Files (x86)\GnuPG\bin
     - C:\Program Files\Git\cmd
     - C:\Program Files\nodejs\
     - C:\soft
     - C:\Ruby25-x64\bin
     - C:\Program Files\Java\jdk-16.0.1\bin
     - C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2021.1.2\bin
     -
     - C:\Program Files\JetBrains\WebStorm 2021.1.2\bin
     -
     - C:\Users\Sachin\AppData\Local\Programs\Microsoft VS Code\bin
     - C:\Program Files\nodejs\
     - C:\Users\Sachin\AppData\Roaming\npm
     - C:\Program Files\JetBrains\RubyMine 2021.2.3\bin
     -
     - C:\Users\Sachin\AppData\Local\Microsoft\WindowsApps

2.
bundle show libxml-ruby 
- >C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/libxml-ruby-2.9.0-x64-mingw32

**Comment by cfis** [comment]
What is the /libxml-ruby-2.9.0-x64-mingw32 directory? Is there actually an libxml-ruby.so file in the correct location?

**Comment by SP8890** [comment]
yes libxml-ruby file in the correct location

**Comment by cfis** [comment]
Well, hard to say without more info. If the file is there, maybe the so file is missing the Init_* call (you can use https://github.com/lucasg/Dependencies to check. Or maybe is a Ruby version mismatch).

**Comment by camilova** [comment]
I have this same error with ruby 3.0.3p157 and rails 7.0 on windows with msys64.
The same app with rails 6.1 and ruby 2.7.5 on the same machine and OS works perfectly.

This is the stacktrace:

C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cac
he/core_ext/kernel_require.rb:34:in `require': cannot load such file -- libxml_r
uby (LoadError)
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/zeitwerk-2.5.3/lib/zeitwerk/
kernel.rb:35:in `require'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/libxml-ruby-3.2.1-x64-mingw3
2/lib/libxml-ruby.rb:8:in `rescue in <main>'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/libxml-ruby-3.2.1-x64-mingw3
2/lib/libxml-ruby.rb:4:in `<main>'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/bootsnap-1.9.3/lib/bootsnap/
load_path_cache/core_ext/kernel_require.rb:23:in `require'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/bootsnap-1.9.3/lib/bootsnap/
load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap
_lfi'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/bootsnap-1.9.3/lib/bootsnap/
load_path_cache/loaded_features_index.rb:100:in `register'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/bootsnap-1.9.3/lib/bootsnap/
load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/bootsnap-1.9.3/lib/bootsnap/
load_path_cache/core_ext/kernel_require.rb:31:in `require'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/zeitwerk-2.5.3/lib/zeitwerk/
kernel.rb:35:in `require'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/bundler-2.3.4/lib/bundler/ru
ntime.rb:60:in `block (2 levels) in require'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/bundler-2.3.4/lib/bundler/ru
ntime.rb:55:in `each'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/bundler-2.3.4/lib/bundler/ru
ntime.rb:55:in `block in require'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/bundler-2.3.4/lib/bundler/ru
ntime.rb:44:in `each'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/bundler-2.3.4/lib/bundler/ru
ntime.rb:44:in `require'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/bundler-2.3.4/lib/bundler.rb
:176:in `require'
        from c:/app-ruby-3/app/config/application.rb:4:in `<main>'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/bootsnap-1.9.3/lib/bootsnap/
load_path_cache/core_ext/kernel_require.rb:23:in `require'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/bootsnap-1.9.3/lib/bootsnap/
load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap
_lfi'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/bootsnap-1.9.3/lib/bootsnap/
load_path_cache/loaded_features_index.rb:100:in `register'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/bootsnap-1.9.3/lib/bootsnap/
load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/bootsnap-1.9.3/lib/bootsnap/
load_path_cache/core_ext/kernel_require.rb:31:in `require'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/railties-7.0.0/lib/rails/com
mand/actions.rb:22:in `require_application!'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/railties-7.0.0/lib/rails/com
mand/actions.rb:14:in `require_application_and_environment!'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/railties-7.0.0/lib/rails/com
mands/console/console_command.rb:101:in `perform'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/thor-1.1.0/lib/thor/command.
rb:27:in `run'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/thor-1.1.0/lib/thor/invocati
on.rb:127:in `invoke_command'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/thor-1.1.0/lib/thor.rb:392:i
n `dispatch'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/railties-7.0.0/lib/rails/com
mand/base.rb:87:in `perform'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/railties-7.0.0/lib/rails/com
mand.rb:48:in `invoke'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/railties-7.0.0/lib/rails/com
mands.rb:18:in `<main>'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/bootsnap-1.9.3/lib/bootsnap/
load_path_cache/core_ext/kernel_require.rb:23:in `require'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/bootsnap-1.9.3/lib/bootsnap/
load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap
_lfi'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/bootsnap-1.9.3/lib/bootsnap/
load_path_cache/loaded_features_index.rb:100:in `register'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/bootsnap-1.9.3/lib/bootsnap/
load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/bootsnap-1.9.3/lib/bootsnap/
load_path_cache/core_ext/kernel_require.rb:31:in `require'
        from bin/rails:4:in `<main>'
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/bootsnap-1.9.3/lib/bootsnap/load_path_cac
he/core_ext/kernel_require.rb:34:in `require': cannot load such file -- 3.0/libx
ml_ruby (LoadError)
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/zeitwerk-2.5.3/lib/zeitwerk/
kernel.rb:35:in `require'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/libxml-ruby-3.2.1-x64-mingw3
2/lib/libxml-ruby.rb:6:in `<main>'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/bootsnap-1.9.3/lib/bootsnap/
load_path_cache/core_ext/kernel_require.rb:23:in `require'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/bootsnap-1.9.3/lib/bootsnap/
load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap
_lfi'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/bootsnap-1.9.3/lib/bootsnap/
load_path_cache/loaded_features_index.rb:100:in `register'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/bootsnap-1.9.3/lib/bootsnap/
load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/bootsnap-1.9.3/lib/bootsnap/
load_path_cache/core_ext/kernel_require.rb:31:in `require'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/zeitwerk-2.5.3/lib/zeitwerk/
kernel.rb:35:in `require'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/bundler-2.3.4/lib/bundler/ru
ntime.rb:60:in `block (2 levels) in require'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/bundler-2.3.4/lib/bundler/ru
ntime.rb:55:in `each'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/bundler-2.3.4/lib/bundler/ru
ntime.rb:55:in `block in require'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/bundler-2.3.4/lib/bundler/ru
ntime.rb:44:in `each'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/bundler-2.3.4/lib/bundler/ru
ntime.rb:44:in `require'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/bundler-2.3.4/lib/bundler.rb
:176:in `require'
        from c:/app-ruby-3/app/config/application.rb:4:in `<main>'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/bootsnap-1.9.3/lib/bootsnap/
load_path_cache/core_ext/kernel_require.rb:23:in `require'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/bootsnap-1.9.3/lib/bootsnap/
load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap
_lfi'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/bootsnap-1.9.3/lib/bootsnap/
load_path_cache/loaded_features_index.rb:100:in `register'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/bootsnap-1.9.3/lib/bootsnap/
load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/bootsnap-1.9.3/lib/bootsnap/
load_path_cache/core_ext/kernel_require.rb:31:in `require'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/railties-7.0.0/lib/rails/com
mand/actions.rb:22:in `require_application!'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/railties-7.0.0/lib/rails/com
mand/actions.rb:14:in `require_application_and_environment!'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/railties-7.0.0/lib/rails/com
mands/console/console_command.rb:101:in `perform'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/thor-1.1.0/lib/thor/command.
rb:27:in `run'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/thor-1.1.0/lib/thor/invocati
on.rb:127:in `invoke_command'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/thor-1.1.0/lib/thor.rb:392:i
n `dispatch'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/railties-7.0.0/lib/rails/com
mand/base.rb:87:in `perform'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/railties-7.0.0/lib/rails/com
mand.rb:48:in `invoke'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/railties-7.0.0/lib/rails/com
mands.rb:18:in `<main>'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/bootsnap-1.9.3/lib/bootsnap/
load_path_cache/core_ext/kernel_require.rb:23:in `require'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/bootsnap-1.9.3/lib/bootsnap/
load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap
_lfi'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/bootsnap-1.9.3/lib/bootsnap/
load_path_cache/loaded_features_index.rb:100:in `register'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/bootsnap-1.9.3/lib/bootsnap/
load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/bootsnap-1.9.3/lib/bootsnap/
load_path_cache/core_ext/kernel_require.rb:31:in `require'
        from bin/rails:4:in `<main>'

**Comment by SP8890** [comment]
Hi @camilova Thanks for your advise. I was using ruby 2.5.3 earlier, I have tried with ruby 2.7.5 but unfortunately this couldn't resoved the issue. The same error occurs again.  It also seems that this error isn't happnes in ubantu or mac.

**Comment by cfis** [comment]
The easiest way to check:

1. Download this program - https://github.com/lucasg/Dependencies
2. Open its GUI
3. Drop the libxml-ruby.so onto it
4. It will then show you the dll's dependencies. I assume one is missing. The other potential issue is the file isn't exporting the Init_ function (but that seems pretty unlikely),

**Comment by cfis** [comment]
Just released a new version for that includes Ruby 3.0 and 3.1 compiled binaries. See if those work for you.
