### ISSUE TITLE
Memory leak in `path` method

### ISSUE THREAD

**Issue by vovanmozg** [xml4r/libxml-ruby#179]
ruby 3.0.0
libxml-ruby: 3.2.1
libxml: 2.9.10
Debian 11

I added demo (using linux `ps` to measure memory consumption)
https://github.com/vovanmozg/libxml-ruby/blob/cf1cd5cd53d05f6af7f90c8b2ccb879f5c140f19/test/test_xpath.rb#L171-L178

 ```ruby
def test_path_memory
  node = LibXML::XML::Node.new('node')
  p `ps -o rss= -p #{Process.pid}`.to_f
  1000000.times do
    node.path
  end
  p `ps -o rss= -p #{Process.pid}`.to_f
end
```

`path` implementation:
https://github.com/xml4r/libxml-ruby/blob/020367b4f86033e14dc67c05168e92a26480324b/ext/libxml/ruby_xml_node.c#L982

**Comment by vovanmozg** [comment]
Please, take a look at the fast solution
https://github.com/vovanmozg/libxml-ruby/commit/5206247be64bfe253e821f7431a54a42af5f0429

**Comment by cfis** [comment]
That looks good - since you have the code already want to send in a pull request? Otherwise I can do it by hand.

**Comment by vovanmozg** [comment]
I going to do some tests on my project and than to send in a pull request.

**Comment by cfis** [comment]
Sounds good - thanks.

**Comment by vovanmozg** [comment]
https://github.com/xml4r/libxml-ruby/pull/180
