### ISSUE TITLE
Repository website URL (xml4r.github.com) is broken

### ISSUE THREAD

**Issue by generalmimon** [xml4r/libxml-ruby#182]
See https://github.com/xml4r/libxml-ruby:

![image](https://user-images.githubusercontent.com/47499687/152680334-1f54bd1d-35fe-4fd6-9c3f-2f1b2ec1d689.png)

[http://xml4r.github<del>.com</del>/libxml-ruby](http://xml4r.github.com/libxml-ruby) no longer works, it should be probably [http<ins><b>s</b></ins>://xml4r.github<ins><b>.io</b></ins>/libxml-ruby/](https://xml4r.github.io/libxml-ruby/) now.

**Comment by cfis** [comment]
Good point - thanks.

**Comment by cfis** [comment]
Fixed.
