### ISSUE TITLE
xmlGetFeaturesList is deprecated

### ISSUE THREAD

**Issue by nwellnhof** [xml4r/libxml-ruby#184]
`xmlGetFeaturesList` is deprecated. For 10+ years, it was only available when libxml2 was compiled with legacy features (feature macro `LIBXML_LEGACY_ENABLED`). The legacy features will be be disabled by default in future libxml2 releases and eventually removed completely.

From a quick look, `xmlGetFeaturesList` always returns the same list of strings and seems completely useless.

**Comment by cfis** [comment]
Ok - want to make a PR to remove it?

**Comment by nwellnhof** [comment]
Yes, I can do that. Shall I remove the `features` method completely or make it return an empty array?

**Comment by cfis** [comment]
Maybe move it to a compatability.rb file that is not automatically loaded by the gem? And just hard code the result to whatever libxml now returns?

**Comment by nwellnhof** [comment]
> Maybe move it to a compatability.rb file that is not automatically loaded by the gem?

I don't have the in-depth knowledge to make changes like that. All I can offer is to change `rxml_features` in `ruby_xml.c`.

**Comment by cfis** [comment]
Ok, sounds good. Just remove it?

**Comment by nwellnhof** [comment]
I think it should be enough to test for `LIBXML_LEGACY_ENABLED`, see #185.

**Comment by cfis** [comment]
Fixed by #185
