### ISSUE TITLE
Validating an XML file is well-formed

### ISSUE THREAD

**Issue by slimdave** [xml4r/libxml-ruby#188]
This is definitely more of a question about a use case than any kind of problem 😬

I have large XML files, 200MB say, and need to verify that they are just well formed because we've recently had some strange issues of files being corrupted in transmission. The concern is really memory usage in Ruby.

Following the advice in the docs, it looks like XML::Reader is likely to be an efficient approach, and was considering something like this (but reading from a file):
```
reader = XML::Reader.string("<foo><bar>1</bar><bar>2</bar><bar>3</bar></foo>")

begin
  while reader.read
  end

  true
rescue LibXML::XML::Error
  false
end
```

Does that seem reasonable?

**Comment by cfis** [comment]
Yes, I would do that also. You could also use a SAX parser, but that is a bit more difficult API to use.
