### ISSUE TITLE
How close `LibXML::XML::Writer.file`?

### ISSUE THREAD

**Issue by Yegorov** [xml4r/libxml-ruby#189]
Hello! It possible to close file opened by `LibXML::XML::Writer.file`?

```ruby
require 'libxml'

w = LibXML::XML::Writer.file(File.expand_path('~/Desktop/test.xml'))
w.start_document(encoding: LibXML::XML::Encoding::UTF_8)
w.write_element('node-name', 'value')
w.end_document
w.flush
binding.irb # File not written, because it's not closed
```

**Comment by cfis** [comment]
#end_document calls (xmlTextWriterEndDocument)[https://gnome.pages.gitlab.gnome.org/libxml2/devhelp/libxml2-xmlwriter.html#xmlTextWriterEndDocument] which flushes to disk.

**Comment by Yegorov** [comment]
Thanks, but you can run (in irb) and check my snippet? After `end_document` or `flush` file is empty.
