### ISSUE TITLE
New release, pretty please

### ISSUE THREAD

**Issue by mamhoff** [xml4r/libxml-ruby#194]
Thank y'all for your hard work on this gem. It's so useful! 

Some of our dev machines upgraded to libxml2 2.10, and we can't build any released gem on our local machines because of the lack of this commit: https://github.com/xml4r/libxml-ruby/commit/c52cfc6d4000cd4de1b399909424ff15a6814a17 . Would you mind releasing a new version to Rubygems?

**Comment by cfis** [comment]
Yes, will do!

**Comment by cfis** [comment]
Done.
