### ISSUE TITLE
Cannot install 3.2.3 due to missing xlink headers

### ISSUE THREAD

**Issue by thefotios** [xml4r/libxml-ruby#197]
This issue was fixed in https://github.com/xml4r/libxml-ruby/commit/c52cfc6d4000cd4de1b399909424ff15a6814a17 but I think upstream changes in `libxml2` introduced a regression that breaks `3.2.3`. At the very least, this might help some folks not waste time trying to track down the same issue or it may be worth a note in the `README`.

The installation fails with the following errors
```
ruby_xml_node.c:814:3: error: unknown type name ‘xlinkType’
  814 |   xlinkType xlt;
      |   ^~~~~~~~~
ruby_xml_node.c:819:14: error: ‘XLINK_TYPE_NONE’ undeclared (first use in this function)
  819 |   if (xlt == XLINK_TYPE_NONE)
      |              ^~~~~~~~~~~~~~~
ruby_xml_node.c: In function ‘rxml_node_xlink_type_name’:
ruby_xml_node.c:836:3: error: unknown type name ‘xlinkType’
  836 |   xlinkType xlt;
      |   ^~~~~~~~~
ruby_xml_node.c:843:8: error: ‘XLINK_TYPE_NONE’ undeclared (first use in this function)
  843 |   case XLINK_TYPE_NONE:
      |        ^~~~~~~~~~~~~~~
ruby_xml_node.c:845:8: error: ‘XLINK_TYPE_SIMPLE’ undeclared (first use in this function); did you mean ‘XML_SCHEMA_TYPE_SIMPLE’?
  845 |   case XLINK_TYPE_SIMPLE:
      |        ^~~~~~~~~~~~~~~~~
      |        XML_SCHEMA_TYPE_SIMPLE
ruby_xml_node.c:847:8: error: ‘XLINK_TYPE_EXTENDED’ undeclared (first use in this function)
  847 |   case XLINK_TYPE_EXTENDED:
      |        ^~~~~~~~~~~~~~~~~~~
ruby_xml_node.c:849:8: error: ‘XLINK_TYPE_EXTENDED_SET’ undeclared (first use in this function)
  849 |   case XLINK_TYPE_EXTENDED_SET:
      |        ^~~~~~~~~~~~~~~~~~~~~~~
```

It turns out that `libxml-ruby` doesn't `#include <libxml/xlink.h>` so I'm not sure how this was working previously (maybe it was transitively included through something else in `libxml`). I validated everything works if I `<include xlink.h>` in `libxml/globals.h`.

I'm not sure how long the issue has existed since I hadn't reinstalled `libxml-ruby` in a while but I'm currently on Fedora 37 with `libxml 2.10.3`

**Comment by cfis** [comment]
Thanks for the report and good question. The gem did build on linux since I test on Fedora before releases - and there is github action to also test it. So I agree likely an upstream change in libxml2.

Version 3.2.4 hopefully should work, and it only has minor changes from 3.2.3. Or 4.0.0, which removes xpointer support since its deprecated on libxml2. 

I could yank the 3.2.3 gem also if that helps.

**Comment by thefotios** [comment]
Thanks for the quick update! I looked through the changes and we decided to update to 4 anyway.

This gem is recommended by `braintree` (a large credit card processor) so there's a good chance a lot of people have it pinned in the Gemfile.lock. Personally, I wouldn't yank 3.2.3 as that has historically never gone well for anybody... but if you want to make the front page of reddit.... :wink:

**Comment by cfis** [comment]
Ok, going to close this ticket then.
