### ISSUE TITLE
New version broke XML::Document.io

### ISSUE THREAD

**Issue by fade2black** [xml4r/libxml-ruby#210]
libxml-ruby-5.0.0 broke `XML::Document.io` method.
I invoke it using `XML::Document.io(ioobj)` and it fails with
```bash
ruby/3.1.2/lib/ruby/gems/3.1.0/gems/libxml-ruby-5.0.0/lib/libxml/parser.rb:60:in `io': wrong number of arguments (given 2, expected 1) (ArgumentError)
        from /Users/bayramkuliyev/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/libxml-ruby-5.0.0/lib/libxml/document.rb:55:in `io'
        from main.rb:82:in `extract'
        from main.rb:108:in `handler'
        from main.rb:113:in `<main>'
```
It is probably because `def self.io(io, options = {})` changed to `def self.io(io, base_uri: nil, encoding: nil, options: nil)` in `parser.rb`.
Maybe you should use `Parser.io(value, **options).parse` instead of `Parser.io(value, options).parse` in document.rb:55 or ? Or do I miss something?

**Comment by cfis** [comment]
Yes, that is correct, and a breaking change (thus the 5.0.0 version). Passing options was switched to use named parameters instead of the old style of passing hashes (see the release notes).  You'll have to update your code. Sorry for the breakage, but this seemed like the right time to do the API change.

**Comment by fade2black** [comment]
Sorry, I couldn't find a place in the documentation where it says that we need to pass keyword params. [Here]?(https://xml4r.github.io/libxml-ruby/LibXML/XML/Document.html#method-c-io)  (link from the github page).

Well, [this](https://github.com/xml4r/libxml-ruby/blob/f2250717f168b1bb44678cc2b693702af52ff4ec/lib/libxml/document.rb#L54) is how the the method `io` is defined:
```ruby
module LibXML
  module XML
    class Document
     #...
     def self.io(value, options = {})
         Parser.io(value, options).parse
     end
     #...
  end
end
``` 
which invokes this method ([here](https://github.com/xml4r/libxml-ruby/blob/f2250717f168b1bb44678cc2b693702af52ff4ec/lib/libxml/parser.rb#L60)
```ruby
module LibXML
  module XML
    class Parser
      #...
      def self.io(io, base_uri: nil, encoding: nil, options: nil)
        context = XML::Parser::Context.io(io)
        context.base_uri = base_uri if base_uri
        context.encoding = encoding if encoding
        context.options = options if options
        self.new(context)
      end
      #...
  end
end
```
So, `self.io` methods requires a an IO object and an optional `options`. 

Moreover, I call simply by 
``` ruby 
XML::Document.io(StringIO.new("<xml>Hello, world!</xml>"))
```

**Comment by vseguin** [comment]
Seems like I opened a duplicate but similar query here -> https://github.com/xml4r/libxml-ruby/issues/211

It looks like the library has a bug from what I understand.

**Comment by fade2black** [comment]
@vseguin But @cfis thinks differently, "breaking changes" and closed right away.

**Comment by cfis** [comment]
The note is in the changelog. See https://github.com/xml4r/libxml-ruby/blob/master/HISTORY

FYI #211 is a definitely a bug and fixed.

**Comment by vseguin** [comment]
@fade2black it does seem that @cfis fixed it now, just waiting for a new update to be released 🙌 Thanks for being super-reactive here.

**Comment by fade2black** [comment]
@cfis You wrote to me
> Yes, that is correct, and a breaking change (thus the 5.0.0 version). Passing options was switched to use keyword parameters instead of the old style of passing hashes (see the release notes). You'll have to update your code. Sorry for the breakage, but this seemed like the right time to do the API change to go along with the deprecation of global settings in limbxml2 2.12.

What does that mean? I guess it you should fix, not me to update my APIs.

**Comment by fade2black** [comment]
@cfis FYI I do know very well semver and CO and can tell apart bug from a breaking changes.
