### ISSUE TITLE
Version 5.0.0 breaks in .io method

### ISSUE THREAD

**Issue by vseguin** [xml4r/libxml-ruby#211]
Hello 👋 

It does seem like the library has a regression with the new version.
I've seen https://github.com/xml4r/libxml-ruby/issues/210 - but look at this piece of code

in XML::Document.io, the library code itself is
```
      def self.io(value, options = {})
        Parser.io(value, options).parse
      end
```

And it does seem to call this in parser.rb
```
      def self.io(io, base_uri: nil, encoding: nil, options: nil)
        context = XML::Parser::Context.io(io)
        context.base_uri = base_uri if base_uri
        context.encoding = encoding if encoding
        context.options = options if options
        self.new(context)
      end
```

Which does not respect its own interface. For context, we are using rspreadsheet, which internally calls the following
```
LibXML::XML::Document.io zip.get_input_stream(CONTENT_FILE_NAME)
```

Which does seem like it should continue working as is, and that the library itself has a bug.

**Comment by cfis** [comment]
Yes you are right, missed that one. Thanks for the report!

**Comment by vseguin** [comment]
> Yes you are right, missed that one. Thanks for the report!

Thanks @cfis ! Will wait for a new patch to update 👍

**Comment by cfis** [comment]
Done. Thanks for testing!
