### ISSUE TITLE
Specified module could not be found (Windows)

### ISSUE THREAD

**Issue by Blackmist** [xml4r/libxml-ruby#42]
Using either the binary version or building the gem myself, I get the following error when trying to use 2.3.3:

`C:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require':
126: The specified module could not be found.   - C:/Ruby193/lib/ruby/gems/1.9.1/gems/libxml-ruby-2.3.3/lib/libxml_ruby.so (LoadError)
`        from C:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in 'require'
`from C:/Ruby193/lib/ruby/gems/1.9.1/gems/libxml-ruby-2.3.3/lib/libxml.rb:8:in 'rescue in <top (required)>'
`        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/libxml-ruby-2.3.3/lib/libxml.rb:4:in '<top (required)>'
`from C:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:60:in 'require'
`        from C:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:60:in 'rescue in require'
`from C:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:35:in 'require'
`        from blah.rb:1:in '<main>'

I've tried with the 1.9.x version of both railsinstaller and rubyinstaller with the same result. It looks like it has something to do with the require "#{$1}/libxml_ruby" statement in lib/libxml.rb, but I'm unsure what the fix should be for this.

**Comment by PositiveAlex** [comment]
@starrychloe this still isn't fixed

**Comment by KapilMetacube** [comment]
Any update on this
I'm not able to resolve this issue with the above-mentioned solutions.
`ENV['PATH'] = ENV['PATH'] + ';' + File.expand_path(File.dirname(FILE) + '/libs')` raises undefined File error. However I used the absolute path and still no luck.
Copying the `libiconv-2.dll` as well as `libxml2-2.dll` in  `C:\Ruby24-x64\bin` also didn't help
#91 #114 seems to share the same issue, but no help from there too.
Please help
This gem is a dependency for twilio-ruby that I'm using and stuck.

OS: Windows 10
Ruby version: 2.4
