### ISSUE TITLE
can't install libxml-ruby (2.4.0 and 2.4.6)

### ISSUE THREAD

**Issue by user21** [xml4r/libxml-ruby#55]
Hello! I am use bitnami stack redmine and want install libxml-ruby gem. 

I run this command gem install -p -f libxml-ruby and get this error:

ERROR:  Error installing libxml-ruby:
        ERROR: Failed to build gem native extension.

```
    /usr/local/redmine/ruby/bin/ruby extconf.rb
```

checking for socket() in -lsocket... no
checking for gethostbyname() in -lnsl... yes
checking for atan() in -lm... no
checking for atan() in -lm... yes
checking for inflate() in -lz... yes
checking for iconv_open() in -liconv... yes
checking for xmlParseDoc() in -lxml2... yes
checking for libxml/xmlversion.h... no
checking for libxml/xmlversion.h in /opt/include/libxml2,/usr/local/include/libxml2,/usr/include/libxml2... no
**\* extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of
necessary libraries and/or headers.  Check the mkmf.log file for more
details.  You may need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/usr/local/redmine/ruby/bin/ruby
        --with-iconv-dir
        --without-iconv-dir
        --with-iconv-include
        --without-iconv-include=${iconv-dir}/include
        --with-iconv-lib
        --without-iconv-lib=${iconv-dir}/lib
        --with-zlib-dir
        --without-zlib-dir
        --with-zlib-include
        --without-zlib-include=${zlib-dir}/include
        --with-zlib-lib
        --without-zlib-lib=${zlib-dir}/lib
        --with-socketlib
        --without-socketlib
        --with-nsllib
        --without-nsllib
        --with-mlib
        --without-mlib
        --with-mlib
        --without-mlib
        --with-zlib
        --without-zlib
        --with-iconvlib
        --without-iconvlib
        --with-xml2-config
        --without-xml2-config
        --with-xml2-dir
        --without-xml2-dir
        --with-xml2-include
        --without-xml2-include=${xml2-dir}/include
        --with-xml2-lib
        --without-xml2-lib=${xml2-dir}/lib
        --with-xml2lib
        --without-xml2lib
 extconf failure: need libxml2.

```
Install the library or try one of the following options to extconf.rb:

  --with-xml2-config=/path/to/xml2-config
  --with-xml2-dir=/path/to/libxml2
  --with-xml2-lib=/path/to/libxml2/lib
  --with-xml2-include=/path/to/libxml2/include
```

Gem files will remain installed in /usr/local/redmine/ruby/lib/ruby/gems/1.8/gems/libxml-ruby-2.4.0 for inspection.
Results logged to /usr/local/redmine/ruby/lib/ruby/gems/1.8/gems/libxml-ruby-2.4.0/ext/libxml/gem_make.out

How can i resolve this problem?
Thanks!

**Comment by muskanregmi** [comment]
@rubykolaveridi007 
Could you please share your experience, how did you fix that issue? I am getting the same error.

**Comment by taogone** [comment]
I have same error. ㅠㅠ
