### ISSUE TITLE
Multithreading instability

### ISSUE THREAD

**Issue by mperham** [xml4r/libxml-ruby#58]
I've gotten a report or two of people seeing instability when using libxml with Sidekiq, e.g mperham/sidekiq#857.  I looked through the docs and noticed that it says the library should call `xmlInitParser` when initializing the library but don't see that called anywhere in libxml-ruby.

This is what I'm referencing:

http://xmlsoft.org/threads.html

Any other possible threading issues my users should know about?

**Comment by cfis** [comment]
Sorry this never happened...that code has been added.
