### ISSUE TITLE
Error: version `LIBXML2_2.9.0' not found 

### ISSUE THREAD

**Issue by JohnBat26** [xml4r/libxml-ruby#70]
Hi.
I use nokogiri at Gentoo linux x86-64.
and I has had next version libxml2:

dev-libs/libxml2
     Available versions:  (2) *2.8.0-r3 2.9.0-r2 ~2.9.1 2.9.1-r1
        {debug doc examples icu ipv6 lzma python readline static-libs test PYTHON_TARGETS="python2_5 python2_6 python2_7 python3_1 python3_2 python3_3"}
     Installed versions:  2.9.1-r1(2)(13:34:43 13.07.2013)(icu ipv6 python readline -debug -examples -lzma -static-libs -test PYTHON_TARGETS="python2_7 -python2_5 -python2_6 -python3_1 -python3_2 -python3_3")

But I get next error: https://gist.github.com/JohnBat26/6003246
Why?

**Comment by cfis** [comment]
Going to close this since it seems like a Nokogiri issue.
