### ISSUE TITLE
2.3.3 fails to build on OsX

### ISSUE THREAD

**Issue by deathowl** [xml4r/libxml-ruby#75]
Installing libxml-ruby (2.3.3)
Gem::Installer::ExtensionBuildError: ERROR: Failed to build gem native extension.

    /Users/deathowl/.rvm/rubies/ruby-1.9.3-p429/bin/ruby extconf.rb
extconf.rb:17: Use RbConfig instead of obsolete and deprecated Config.
checking for socket() in -lsocket... no
checking for gethostbyname() in -lnsl... no
checking for atan() in -lm... no
checking for atan() in -lm... yes
checking for inflate() in -lz... yes
checking for iconv_open() in -liconv... no
checking for libiconv_open() in -liconv... yes
checking for xmlParseDoc() in -lxml2... yes
checking for libxml/xmlversion.h... yes
creating extconf.h
creating Makefile

make
compiling libxml.c
compiling ruby_xml.c
ruby_xml.c: In function 'rxml_default_tree_indent_string_set':
ruby_xml.c:612: warning: pointer targets in assignment differ in signedness
compiling ruby_xml_attr.c
compiling ruby_xml_attr_decl.c
ruby_xml_attr_decl.c: In function 'rxml_attr_decl_name_get':
ruby_xml_attr_decl.c:57: warning: pointer targets in passing argument 2 of 'rxml_new_cstr' differ in signedness
compiling ruby_xml_attributes.c
compiling ruby_xml_cbg.c
ruby_xml_cbg.c: In function 'deb_Open':
ruby_xml_cbg.c:50: warning: implicit conversion shortens 64-bit value into a 32-bit value
compiling ruby_xml_document.c
ruby_xml_document.c: In function 'rxml_document_canonicalize':
ruby_xml_document.c:259: warning: implicit conversion shortens 64-bit value into a 32-bit value
ruby_xml_document.c:303: warning: implicit conversion shortens 64-bit value into a 32-bit value
ruby_xml_document.c:232: warning: unused variable 'list_in'
ruby_xml_document.c:334: warning: passing argument 4 of 'xmlC14NDocDumpMemory' from incompatible pointer type
ruby_xml_document.c:334: warning: implicit conversion shortens 64-bit value into a 32-bit value
ruby_xml_document.c: In function 'rxml_document_save':
ruby_xml_document.c:805: warning: pointer targets in assignment differ in signedness
compiling ruby_xml_dtd.c
compiling ruby_xml_encoding.c
compiling ruby_xml_error.c
compiling ruby_xml_html_parser.c
compiling ruby_xml_html_parser_context.c
ruby_xml_html_parser_context.c: In function 'rxml_html_parser_context_string':
ruby_xml_html_parser_context.c:235: warning: implicit conversion shortens 64-bit value into a 32-bit value
compiling ruby_xml_html_parser_options.c
compiling ruby_xml_input_cbg.c
ruby_xml_input_cbg.c: In function 'ic_open':
ruby_xml_input_cbg.c:49: warning: implicit conversion shortens 64-bit value into a 32-bit value
ruby_xml_input_cbg.c: In function 'input_callbacks_add_scheme':
ruby_xml_input_cbg.c:113: warning: implicit conversion shortens 64-bit value into a 32-bit value
compiling ruby_xml_io.c
ruby_xml_io.c: In function 'rxml_read_callback':
ruby_xml_io.c:19: warning: implicit conversion shortens 64-bit value into a 32-bit value
compiling ruby_xml_namespace.c
compiling ruby_xml_namespaces.c
compiling ruby_xml_node.c
ruby_xml_node.c: In function 'rxml_node_new_cdata':
ruby_xml_node.c:151: warning: implicit conversion shortens 64-bit value into a 32-bit value
ruby_xml_node.c: In function 'rxml_node_to_s':
ruby_xml_node.c:622: error: dereferencing pointer to incomplete type
ruby_xml_node.c:624: error: dereferencing pointer to incomplete type
make: *** [ruby_xml_node.o] Error 1

Gem files will remain installed in /Users/deathowl/.rvm/gems/ruby-1.9.3-p429/gems/libxml-ruby-2.3.3 for inspection.
Results logged to /Users/deathowl/.rvm/gems/ruby-1.9.3-p429/gems/libxml-ruby-2.3.3/ext/libxml/gem_make.out

**Comment by cfis** [comment]
Going to close this.
