### ISSUE TITLE
2.3.3 does not build on Arch

### ISSUE THREAD

**Issue by jmatraszek** [xml4r/libxml-ruby#80]
Libxml2 version 2.9.1-5. Here is the output from gem install libxml-ruby -v '2.3.3':
http://pastie.org/8512073

**Comment by brpocock** [comment]
Seeing similar errors on CentOS 7. Was there any resolution to this?

**Comment by brpocock** [comment]
I should mention — that's CentOS7, Ruby 1.8.7, libxml-ruby 2.3.3 from "gem install" or "bundle install"

**Comment by cfis** [comment]
Hopefully this latch patch solves.
