### ISSUE TITLE
Typos in README.rdoc section Memory management

### ISSUE THREAD

**Issue by qnet-herwin** [xml4r/libxml-ruby#82]
If doc2 is freed before node2 a segmentatin fault will occur...

The code example above doesn't have variable node2, this should probably be node

    Alternatively, you can call node2.remove! to disassociate node2 from doc2.

Once again, there is no node2 in the code snippet. This time, there isn't a node either.

**Comment by cfis** [comment]
Thanks.  Fixed in de62f33248c3fe677197d6d66c05ae5385bba396.
