### ISSUE TITLE
Segmentation Fault in XML::Parser

### ISSUE THREAD

**Issue by saneshark** [xml4r/libxml-ruby#87]
I am trying to track down recurring segmentation fault in a production app, and while I'm not convinced that addressing the failing test indicated here would solve my problem, I thought I should mention it.

The following resulted in a Segmentation Fault using ruby-1.9.3-p545:

```
require 'xml'

XMLFEED = <<-XMLFEED
<?xml version="1.0" encoding="UTF-8"?>
<example>
	<parse1>Parse twice you get an parse1</parse1>
	<parse2>Parse thrice you get a SEGFAULT!!!</parse2>
</example>
XMLFEED


xml_object = XML::Parser.string(XMLFEED)
puts "\nFirst Time"
begin
	doc = xml_object.parse
	puts doc.inspect
rescue => e
	puts e.message
end

puts "\nSecond Time"
begin
	doc = xml_object.parse
	puts doc.inspect
rescue => e
	puts e.message
end
puts

puts "\nThird Time"
begin
	doc = xml_object.parse
	puts doc.inspect
rescue => e
	puts e.message
end
```

I'm no expert at running kernel level debuggers, but I think I may have tracked down the issue to the following methods using valgrind:

```
==28223== Invalid read of size 8
==28223==    at 0xA3AF4F: xmlDictFree (in /usr/lib/libxml2.2.dylib)
==28223==    by 0xA6CE56: xmlFreeParserCtxt (in /usr/lib/libxml2.2.dylib)

Invalid free() / delete / delete[] / realloc()
==28223==    at 0x7237: free (in /usr/local/Cellar/valgrind/3.9.0/lib/valgrind/vgpreload_memcheck-amd64-darwin.so)
==28223==    by 0xA6CE56: xmlFreeParserCtxt (in /usr/lib/libxml2.2.dylib)
```

**Comment by codekitchen** [comment]
I ran across this because I'm trying to track down a segfault that I also thought might be a conflict between nokogiri and libxml. But this test case segfaults for me even without nokogiri loaded, just libxml-ruby, so this one doesn't look like a conflict.

**Comment by cfis** [comment]
See #116.
