### ISSUE TITLE
libxml-ruby windows install

### ISSUE THREAD

**Issue by Dharam64** [xml4r/libxml-ruby#91]
I have been trying to install libxml-ruby on windows:

As mentioned in the INSTALLATION step in this link:
https://github.com/xml4r/libxml-ruby

Installed:
gem install win-user32-ruby

Can anyone help me understand the below line:
"Note these binaries are available in the liblibs directory. To use them, put them someplace on your path."

Where do i find the liblib directory and do you mean the rails path by someplace on your path?

Thsi is my current win32 ruby gems path:C:\RailsInstaller\Ruby1.9.3\lib\ruby\gems\1.9.1\gems\win32console-1.3.2-x86-mingw32\lib
and i don't see this lib\lib folder

**Comment by pbennett** [comment]
So how are windows users supposed to install this gem?

**Comment by wstrinz** [comment]
I've dug into this for the past couple nights and have come up with a fix that works for me on Windows 64 bit w/ ruby 2.2: http://stackoverflow.com/questions/22417544/having-trouble-installing-libxml-ruby-on-windows/33685307#33685307

good luck :smile:

**Comment by Ruin0x11** [comment]
I managed to compile and install the gem by following the above, but it fails to load on `require`:

     irb(main):001:0> require 'libxml'
     LoadError: 126: The specified module could not be found.   - C:/Ruby22-x64/lib/ruby/gems/2.2.0/extensions/x64-mingw32/2.2.0/libxml-ruby-2.8.0/libxml_ruby.so
             from C:/Ruby22-x64/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
             from C:/Ruby22-x64/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
             from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/libxml-ruby-2.8.0/lib/libxml.rb:8:in `rescue in <top (required)>'
             from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/libxml-ruby-2.8.0/lib/libxml.rb:4:in `<top (required)>'
             from C:/Ruby22-x64/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `require'
             from C:/Ruby22-x64/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `rescue in require'
             from C:/Ruby22-x64/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:39:in `require'
             from (irb):1
             from C:/Ruby22-x64/bin/irb:11:in `<main>'


I tried moving `libxml2-2.dll` to a folder on the PATH, but it still doesn't work.

I'm starting to think binary gem would be nice at this point.

**Comment by pbennett** [comment]
Still out of luck for Ruby 2.2/32-bit (would do 64-bit but it's still not recommended by RubyInstaller maintainers).  The lib still depends on iconv which was dropped by Ruby itself in 2.0.   This is one of the few gems that seems to always be behind.  Users are basically on their own for 2.1 and 2.2. :(

**Comment by cfis** [comment]
For 2.9.0, I added back in 64 bit binaries for mingw64 and Ruby 2.3.1
