### ISSUE TITLE
DTD validation ignores undefined entities

### ISSUE THREAD

**Issue by captn3m0** [xml4r/libxml-ruby#93]
The gist of this is that the DTD validation method returns true even if any unknown entities are encountered in the XML document. 

Right now, as a workaround, I might hook into the XML error handler to catch the undefined entities myself, but that feels like the wrong way to go about things.

Is there a better way to accomplish this, or am I missing something obvious?

```rb
require 'xml'

xml = <<END
<?xml version=\"1.0\" encoding=\"UTF-8\"?>
<!DOCTYPE document SYSTEM \"http://xml.evernote.com/pub/enml2.dtd\">
<document>&nbsp; &hello;</document>
END

# Note that the hellp entity is not defined
dtd = <<END
<!ELEMENT document (#PCDATA)>
<!ENTITY nbsp "value">
END
dtd = XML::Dtd.new dtd

XML::Error.set_handler do |err|
  # This is to show that the XML parser catches this as an error
  puts err.code_to_s
  puts err
end

# Call the XML parser
doc = XML::Document.string xml

# While the validator simply accepts the undefined entity as vallid
# and returns true
puts doc.validate dtd
```

**Comment by cfis** [comment]
Look at tc_dtd.rb line 73-75.  An exception is raised.

I think in this case one is not, because the original document is not valid and libxml flags that as an error.  So maybe the 2nd time it doesn't?
